- block:
  - name: enable GigabitEthernet1 interface if compliant on r2
    ios_interface:
      name: GigabitEthernet1
      description: interface to host1
      state: present

  - name: dhcp configuration for GigabitEthernet1
    ios_config:
      lines:
        - ip address dhcp
      parents: interface GigabitEthernet1
